### PR TITLE
Mod 5 Week 1 Assessment

### LINKED ISSUE #325: Week 1 Assessment

### PR DESCRIPTION
**Pull request by memcmahon**

### CODE REVIEW

**Comment by zoefarrell** [comment]
Instead of "Data Validations and Logging" I think we want "Error Handling and Logging" and things like null checks would count here.

**Comment by zoefarrell** [comment]
I think it would help to be a bit more prescriptive about the five improvements. Maybe we say at least one needs to be an error handling improvement and at least one a logging improvement?

**Comment by zoefarrell** [comment]
I think they will probably need to update-database to get this working, I think maybe we still include this in the instructions? I want them to grow independency of debugging, but I don't think an assessment is the best place to do that because it's not a learning goal we're trying to assess.

**Comment by zoefarrell** [comment]
This app you built for debugging is awesome! Love that you added some quality touches in this app like the delete pop-up and some bootstrap. 🎉 I also really like that you have the Serilog logger injected, so they can see that even if they didn't build it that way during the lesson. And there are so many improvements for them to find with the log level being incorrect and things like that 👏 

I'm especially excited for them to do an assessment review on this to see the different things they each found! I think it'll be great learning all around as well as a good checkpoint.

**Review by zoefarrell — APPROVED** [review]

**Review by zoefarrell — APPROVED** [review]

**Comment by memcmahon** [comment]
haha - will I **ever** remember that it should be error-handling... probably not 🙃 

And I agree on the prescriptiveness - I think I might say at least 2 of each type.

**Pull request merged**
